spring:
  cloud:
    config:
      uri: http://119.3.25.215:8888
  redis:
    database: 0
    host: 172.17.0.2
    port: 6379
    password: elementspeed
  session:
    store-type: redis
  cache:
    cache-names: dic
mybatis:
# 自动分页插件pageHelper需要设置该属性
  typeAliasesPackage: com.isea533.ssm.model
  mapperLocations: classpath*:com/elementspeed/**/mapper/mysql/**/*.xml
  configLocation: classpath:config/mybatis/MyBatis-Configuration.xml

# 显示SQL
logging:
  level:
    com:
      elementspeed: debug

#eureka客户端
eureka:
  client:
    serviceUrl:
      defaultZone: http://119.3.25.215:8761/eureka     


